### ISSUE TITLE
Add Metador Logo

### ISSUE THREAD

**Issue by Metador-SMARTBCH** [mistswapdex/assets#39]
Contract Address: 0x7e56d225f69a5b0d1c2fc47673a5c41328fc82e0
![logo](https://user-images.githubusercontent.com/95138869/146328792-c484c19d-a9ae-4cdf-9c83-ff06952a9392.png)

**Comment by kasumi-1** [comment]
Added in b40eee2f101b349ad43c3f4d2383421f6d5947a3 thanks
