### ISSUE TITLE
Please Add BabyLaw logo 

### ISSUE THREAD

**Issue by Diggle187** [mistswapdex/assets#44]
CA - 0x02905c38B3CFBAE5255104C7a6FD10EF78225f35

![72C09C4C-CF74-4951-B118-EED2C5E7AA2F](https://user-images.githubusercontent.com/90625656/147785306-7ca62482-7225-4dca-b244-39b8b7929e74.jpeg)

**Comment by kasumi-1** [comment]
Added in 5b2c8656ee29f1de14f6a32ea740a74b229acf91 thanks
