### ISSUE TITLE
Update Metador Logo

### ISSUE THREAD

**Issue by Metador-SMARTBCH** [mistswapdex/assets#47]
Contract Address: 0x7e56d225f69a5b0d1c2fc47673a5c41328fc82e0
![logo-small](https://user-images.githubusercontent.com/95138869/147870701-7dc7eb8f-19d6-4b25-a5cc-3d3188664f10.png)

**Comment by kasumi-1** [comment]
Hi! Please send square image.

**Comment by Metador-SMARTBCH** [comment]
![Uploading square-logo.png…]()

**Comment by Metador-SMARTBCH** [comment]
![logoo-meta](https://user-images.githubusercontent.com/95138869/148176090-a80698e9-f06b-459d-aefb-ec0f3ff5c597.png)

This is 256*256 picture.

**Comment by Metador-SMARTBCH** [comment]
![logo-small](https://user-images.githubusercontent.com/95138869/148176760-e6ad2f3d-eef6-4413-acdf-e554aaf47bc5.png)
